
server:
  port: 9001


spring:
  cloud:
    gateway:
      routes:
      - id: gateway-route
        uri: http://localhost:8088
        predicates:
        - Path=/hello


#  上面这段配置的意思是，配置了一个 id 为 gateway-route 的路由规则，
#  当访问地址 http://localhost:9001/hello 时会自动转发到地址：
#  http://localhost:8088/hello

#  id：我们自定义的路由 ID，保持唯一
#  uri：目标服务地址
#  predicates：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
#  filters：过滤规则，本示例暂时没用。